[tool.poetry]
name = "nanoPPO"
version = "0.15.post1"
description = "A flexible and efficient implementation of the Proximal Policy Optimization (PPO) algorithm for reinforcement learning."
readme = "README.md"
authors = ["James Liu"]
license = "Apache-2.0"

[tool.poetry.extras]
test = ["pytest"]
